@url_dev = http://localhost:3056/v1/api

### Signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
  "name": "Shop TIPS223",
  "email": "shoptipsjs2133@gmail.com",
  "password": "abc123"
}